name = "NormalHermiteSplines"
uuid = "67f7b941-d455-546b-99f0-07b665bf0aaf"
keywords = ["interpolation", "splines", "hermite-splines", "normal-splines", "approximation", "rkhs"]
authors = ["Igor Kohanovsky <nettvor@gmail.com>"]
version = "0.6.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[compat]
Aqua = "0.8"
DoubleFloats = "1.3"
ForwardDiff = "0.10"
LinearAlgebra = "1"
MuladdMacro = "0.2"
Random = "1"
StaticArrays = "1"
Test = "1"
UnsafeArrays = "1.0"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "DoubleFloats", "ForwardDiff", "Random", "Test"]
