name = "NormalHermiteSplines"
uuid = "67f7b941-d455-546b-99f0-07b665bf0aaf"
keywords = ["interpolation", "splines", "hermite-splines", "normal-splines", "approximation", "rkhs"]
authors = ["Igor Kohanovsky <nettvor@gmail.com>"]
version = "0.6.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6"

[extras]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DoubleFloats", "Test"]
